---
name: 问题反馈
description: 反馈 BUG 帮助我们改进 VanBlog
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述 | Describe the bug
      description: 请描述你的问题现象 | A clear and concise description of what the bug is.
      placeholder:
      value:
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 问题网站 | Website URL
      description: 请提供下可复现网站地址 | Please supply a website url which can reproduce problem.
      placeholder: ex. https://blog-demo.mereith.com
    validations:
      required: false

  - type: markdown
    id: version
    attributes:
      value: |
        ## 版本 | Version

  - type: dropdown
    id: deployMethod
    validations:
      required: true
    attributes:
      label: 部署方式？ | How do you deploy vanblog?
      description:
      options:
        - Docker (default)
        - Manual
        - Other


