version: "3"

services:
  server:
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:server-1.0.0
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      VAN_BLOG_DATABASE_URL: "mongodb://vanBlog:vanBlog@mongo:27017"
      VAN_BLOG_JWT_SECRET: "AnyString"
  admin:
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:admin-1.0.0
    restart: always
    environment:
      TZ: "Asia/Shanghai"
  website:
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:website-1.0.0
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      VAN_BLOG_SERVER_URL: "http://server:3000"
      VAN_BLOG_REVALIDATE_TIME: 10
      VAN_BLOG_ALLOW_DOMAINS: "pic.mereith.com"
  proxy:
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:proxy
    restart: always
    ports:
      - 8360:80
    environment:
      TZ: "Asia/Shanghai"
      VAN_BLOG_SERVER_HOST: "server:3000"
      VAN_BLOG_WEBSITE_HOST: "website:3001"
      VAN_BLOG_ADMIN_HOST: "admin:3002"
  mongo:
    image: mongo
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MONGO_INITDB_ROOT_USERNAME: vanBlog
      MONGO_INITDB_ROOT_PASSWORD: vanBlog
    volumes:
      - $(pwd)/data/mongo:/data/db
  # 如果你需要评论系统就加上
  # waline:
  #   image: lizheming/waline:latest
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8360:8360
  #   volumes:
  #     - /var/docker/waline/data:/app/data
  #   environment:
  #     TZ: 'Asia/Shanghai'
  #     SITE_NAME: 'Mereith Blog'
  #     SITE_URL: 'https://www.mereith.com'
  #     SECURE_DOMAINS: 'mereith.com'
  #     AUTHOR_EMAIL: 'wanglu@mereith.com'
  #     MONGO_HOST: "tx4.mereith.top"
  #     MONGO_DB: "waline"
  #     MONGO_USER: "mereith"
  #     MONGO_PASSWORD: "vanlusg2!"
  #     MONGO_AUTHSOURCE: "admin"
