version: "3"

services:
  vanblog:
    # 默认国内原的
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:latest
    # image: mereith/van-blog:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      # 图片资源允许的域名，英文逗号分隔
      VAN_BLOG_ALLOW_DOMAINS: "pic.mereith.com"
      # CDN URL，包含协议，部署到 cdn 的时候用。
      VAN_BLOG_CDN_URL: "https://www.mereith.com"
      # mongodb 的地址
      VAN_BLOG_DATABASE_URL: "mongodb://vanBlog:vanBlog@mongo:27017"
      # jwt 密钥，随机字符串即可
      VAN_BLOG_JWT_SECRET: "AnyString"
      # 邮箱地址，用于自动申请 https 证书
      EMAIL: "someone@mereith.com"
    volumes:
      # 图床文件的存放地址，按需修改。
      - ${PWD}/data/static:/app/static
      # 日志文件
      - ${PWD}/log:/var/log
      # caddy 配置存储
      - ${PWD}/caddy/config:/root/.config/caddy
      # caddy 证书存储
      - ${PWD}/caddy/data:/root/.local/share/caddy
    ports:
      - 80:80
      - 443:443
  mongo:
    image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:mongo
    # image: mongo
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MONGO_INITDB_ROOT_USERNAME: vanBlog
      MONGO_INITDB_ROOT_PASSWORD: vanBlog
    volumes:
      - ${PWD}/data/mongo:/data/db
  # 如果你需要评论系统就加上
  # https://waline.js.org/
  # waline:
  #   image: lizheming/waline:latest
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8360:8360
  #   volumes:
  #     - /var/docker/waline/data:/app/data
  #   environment:
  #     TZ: 'Asia/Shanghai'
  #     SITE_NAME: 'Mereith Blog'
  #     SITE_URL: 'https://www.mereith.com'
  #     SECURE_DOMAINS: 'mereith.com'
  #     AUTHOR_EMAIL: 'wanglu@mereith.com'
  #     MONGO_HOST: "tx4.mereith.top"
  #     MONGO_DB: "waline"
  #     MONGO_USER: "mereith"
  #     MONGO_PASSWORD: "vanlusg2!"
  #     MONGO_AUTHSOURCE: "admin"
